name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    # do not remove wheel
    - run: python -m pip install --upgrade pip wheel
    - run: python -m pip install --prefer-binary -e .[test]
    - run: python setup.py sdist bdist_wheel
    - run: python -m pip install --force-reinstall dist/*.tar.gz
    - run: python -m pytest

    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{secrets.PYPI_TOKEN}}
