name: Release

on:
  workflow_dispatch:
  # push:
    # tags:
    #   - 'v*.*.*'

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # - uses: actions/setup-python@v2
    #   with:
    #     python-version: '3.x'
    #
    # - run: |
    #     python -m pip install --upgrade pip
    #     python -m pip install wheel
    #
    # - run: python setup.py sdist bdist_wheel
    #
    # - run: python -m pip install dist/*.whl[test]
    #
    # - run: python -m pytest
    #
    # - uses: pypa/gh-action-pypi-publish@master
    #   with:
    #     user: __token__
    #     password: ${{secrets.PYPI_TOKEN}}

  release:
    runs-on: ubuntu-latest
    needs: [pypi]
    steps:
    - uses: actions/checkout@v2

    - uses: softprops/action-gh-release@v1
      env:
        draft: True
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
